### PR TITLE
added phone number regex validator.

### LINKED ISSUE #218: Phone field accepts invalid phone number formats
Starting point: http://dev.rohelp.ro/en/admin/hub/ngo/

**Expected**:
When adding a NGO, Phone field should accept only phone number formats consisting of digits only with or without plus sign.

**Actual**:
When adding a NGO, Phone field appears as a requirement, though it accepts invalid phone number formats, characters or even email address. 

Screenshot 2020-04-01 at 17 24 27

Screenshot 2020-04-01 at 17 23 36

Screenshot 2020-04-01 at 17 25 21

### PR DESCRIPTION
**Pull request by AlecsGherghel**
### What does it fix?

Closes #218 

Added a new validator for `phone` field from `NGO` model.

### CODE REVIEW

**Comment by AlecsGherghel** [comment]
@catileptic Do we want to use the same validation logic for **all** phone fields?

I see that we also have:

- `PaymentOrder.phone`
- `NGOHelper.phone`
- `PersonalRequest.phone`
- `RegisterNGORequest.phone`

**Comment by catileptic** [comment]
Let's not merge this yet. The regexp doesn't support numbers that start with anything other than +4 (or doesn't have the country code).

**Comment by aramboi** [comment]
Rather than adding our custom regex in the models, maybe it would be better to use a Django app like https://github.com/stefanfoulis/django-phonenumber-field that lets you choose from one of the standardized formats. Underneath it relies on a python port of the Google phone number library used in Android and it has support for national and international number formatting.

**Comment by AlecsGherghel** [comment]
@aramboi That looks good! At the time of creating this PR I was looking for a quick turnaround without adding a new project dependency.

But now that the project is doing well live, I think that relying on existing libraries sounds like a great idea :)

I'll be closing this in the meantime and when there's a decision around the path going forward I'll either re-open a different one or maybe someone else will do it.

**Pull request closed without merging**
